// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"
)

type Device struct {
	Imei             string
	BatteryPower     int64
	Charging         bool
	LastStatusPacket time.Time
}

type Position struct {
	ID         interface{}
	Latitude   float64
	Longitude  float64
	Speed      int64
	Heading    int64
	DeviceImei string
	CreatedAt  time.Time
}

type User struct {
	ID            string
	Email         string
	Password      string
	LastLoginTime time.Time
}

type UserDevice struct {
	Userid     string
	DeviceImei string
}
