// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package database

import (
	"context"
)

const createPosition = `-- name: CreatePosition :exec
INSERT INTO positions (latitude,longitude,speed,heading,device_imei)
VALUES ($1,$2,$3,$4,$5)
`

type CreatePositionParams struct {
	Latitude   float64
	Longitude  float64
	Speed      int16
	Heading    int16
	DeviceImei string
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) error {
	_, err := q.db.ExecContext(ctx, createPosition,
		arg.Latitude,
		arg.Longitude,
		arg.Speed,
		arg.Heading,
		arg.DeviceImei,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id,name,email,avatar) VALUES ($1,$2,$3,$4) RETURNING id, name, email, avatar, last_login_time
`

type CreateUserParams struct {
	ID     string
	Name   string
	Email  string
	Avatar string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.LastLoginTime,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, avatar, last_login_time FROM users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Avatar,
		&i.LastLoginTime,
	)
	return i, err
}

const insertDevice = `-- name: InsertDevice :one
INSERT INTO devices (imei,battery_power,charging) VALUES ($1,$2,$3) RETURNING imei, battery_power, charging, last_status_packet
`

type InsertDeviceParams struct {
	Imei         string
	BatteryPower int16
	Charging     bool
}

func (q *Queries) InsertDevice(ctx context.Context, arg InsertDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, insertDevice, arg.Imei, arg.BatteryPower, arg.Charging)
	var i Device
	err := row.Scan(
		&i.Imei,
		&i.BatteryPower,
		&i.Charging,
		&i.LastStatusPacket,
	)
	return i, err
}

const linkDevice = `-- name: LinkDevice :exec
INSERT INTO user_devices (userid,device_imei) VALUES ($1,$2)
`

type LinkDeviceParams struct {
	Userid     string
	DeviceImei string
}

func (q *Queries) LinkDevice(ctx context.Context, arg LinkDeviceParams) error {
	_, err := q.db.ExecContext(ctx, linkDevice, arg.Userid, arg.DeviceImei)
	return err
}

const updateBatteryPower = `-- name: UpdateBatteryPower :exec
UPDATE devices SET battery_power = $1 WHERE imei = $2
`

type UpdateBatteryPowerParams struct {
	BatteryPower int16
	Imei         string
}

func (q *Queries) UpdateBatteryPower(ctx context.Context, arg UpdateBatteryPowerParams) error {
	_, err := q.db.ExecContext(ctx, updateBatteryPower, arg.BatteryPower, arg.Imei)
	return err
}

const updateCharging = `-- name: UpdateCharging :exec
UPDATE devices SET charging = $1 where imei = $2
`

type UpdateChargingParams struct {
	Charging bool
	Imei     string
}

func (q *Queries) UpdateCharging(ctx context.Context, arg UpdateChargingParams) error {
	_, err := q.db.ExecContext(ctx, updateCharging, arg.Charging, arg.Imei)
	return err
}
